/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as DetailIdRouteImport } from './routes/detail.$id'
import { Route as PersonIdRouteImport } from './routes/person.$id'
import { Route as DetailIdCastRouteImport } from './routes/detail.$id.cast'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailIdRoute = DetailIdRouteImport.update({
  id: '/detail/$id',
  path: '/detail/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonIdRoute = PersonIdRouteImport.update({
  id: '/person/$id',
  path: '/person/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailIdCastRoute = DetailIdCastRouteImport.update({
  id: '/cast',
  path: '/cast',
  getParentRoute: () => DetailIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/setup': typeof SetupRoute
  '/trending': typeof TrendingRoute
  '/detail/$id': typeof DetailIdRouteWithChildren
  '/person/$id': typeof PersonIdRoute
  '/detail/$id/cast': typeof DetailIdCastRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/setup': typeof SetupRoute
  '/trending': typeof TrendingRoute
  '/detail/$id': typeof DetailIdRouteWithChildren
  '/person/$id': typeof PersonIdRoute
  '/detail/$id/cast': typeof DetailIdCastRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/setup': typeof SetupRoute
  '/trending': typeof TrendingRoute
  '/detail/$id': typeof DetailIdRouteWithChildren
  '/person/$id': typeof PersonIdRoute
  '/detail/$id/cast': typeof DetailIdCastRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/search'
    | '/setup'
    | '/trending'
    | '/detail/$id'
    | '/person/$id'
    | '/detail/$id/cast'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/search'
    | '/setup'
    | '/trending'
    | '/detail/$id'
    | '/person/$id'
    | '/detail/$id/cast'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/search'
    | '/setup'
    | '/trending'
    | '/detail/$id'
    | '/person/$id'
    | '/detail/$id/cast'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SetupRoute: typeof SetupRoute
  TrendingRoute: typeof TrendingRoute
  DetailIdRoute: typeof DetailIdRouteWithChildren
  PersonIdRoute: typeof PersonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detail/$id': {
      id: '/detail/$id'
      path: '/detail/$id'
      fullPath: '/detail/$id'
      preLoaderRoute: typeof DetailIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/person/$id': {
      id: '/person/$id'
      path: '/person/$id'
      fullPath: '/person/$id'
      preLoaderRoute: typeof PersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detail/$id/cast': {
      id: '/detail/$id/cast'
      path: '/cast'
      fullPath: '/detail/$id/cast'
      preLoaderRoute: typeof DetailIdCastRouteImport
      parentRoute: typeof DetailIdRoute
    }
  }
}

interface DetailIdRouteChildren {
  DetailIdCastRoute: typeof DetailIdCastRoute
}

const DetailIdRouteChildren: DetailIdRouteChildren = {
  DetailIdCastRoute: DetailIdCastRoute,
}

const DetailIdRouteWithChildren = DetailIdRoute._addFileChildren(
  DetailIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SetupRoute: SetupRoute,
  TrendingRoute: TrendingRoute,
  DetailIdRoute: DetailIdRouteWithChildren,
  PersonIdRoute: PersonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
